import Head from 'next/head'
import { useRouter } from 'next/router'



export default function RecentlyPlayed() {
    
  return (
    <div>
    <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>
          Recently played tracks
        </h1>
        </div>
    </div>
  )
}

