import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'



export default function CurrentlyPlaying({

}) {

    
  return (
    <div>
    <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>
          Currently Playing
        </h1>
        </div>
    </div>
  )
}

