import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Current.module.css'
import { useEffect, useState } from 'react'



export default function Current() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
  <h1 className={styles.title} style={{ marginTop: 42 }}>Hey, Tordar!</h1>
  <h2 style={{ marginTop: 42 }}>You're currently playing track is: </h2>
  {/* <h2>{currentlyPlaying}, {currentArtist}</h2> */}
  <h2 style={{ marginTop: 42 }}>Here's your recently played tracks:</h2>

      {/* {isLoading && <p>Loading...</p>} */}
      <div className={styles.tileContainer} >
        
      </div>
    </main>
  </div>
  )
}

